global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  # - job_name: "application-platform-thread"
  #   scrape_interval: 1s
  #   metrics_path: "/actuator/prometheus"
  #   static_configs:
  #     - targets: ["host.docker.internal:8090"]

  # - job_name: "application-virtual-thread"
  #   scrape_interval: 1s
  #   metrics_path: "/actuator/prometheus"
  #   static_configs:
  #     - targets: ["host.docker.internal:8091"]

  - job_name: "api-gateway-1"
    scrape_interval: 1s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["10.16.24.120:8080"]

  - job_name: "api-gateway-2"
    scrape_interval: 1s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["10.16.24.121:8080"]
