server:
  port: 8082

spring:
  application:
    name: INSTA-POST-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://insta-service-registry:8761/eureka/

minio:
  url: http://nginx:9002
  access:
    name: ROOTNAME
    secret: CHANGEME123
  bucket:
    name: insta-post-bucket