#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: insta-media-service
#          uri: lb://INSTA-MEDIA-SERVICE
#          predicates:
#            - Path=/media/**
#            - Path=/hello
##          filters:
##            - AuthenticationFilter
#
#        - id: insta-post-service
#          uri: lb://INSTA-POST-SERVICE
#          predicates:
#            - Path=/post/**
##          filters:
##            - AuthenticationFilter
#
##        - id: identity-service
##          uri: lb://IDENTITY-SERVICE
##          predicates:
##            - Path=/auth/**
#
#  application:
#    name: INSTA-GATEWAY-SERVICE
#
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/