# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Project CI/CD Build Flow

on:
  [workflow_dispatch]
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Build insta-service-registry with Maven
        run: |
          cd insta-service-registry
          mvn clean package
          cd ../insta-config-server
          mvn clean package
          cd ../insta-gateway-service
          mvn clean package
          cd ../insta-auth-service
          mvn clean package
          cd ../insta-user-service
          mvn clean package
          cd ../insta-post-service
          mvn clean package
          cd ../insta-media-service
          mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: leezonghan19
          password: Siv170013! # Use DOCKER_ACCESS_TOKEN instead if applicable

      - name: Build and Push Docker Images
        run: |
          cd insta-service-registry
          docker build -t leezonghan19/happysocial-backend:insta-service-registry.latest .
          docker push leezonghan19/happysocial-backend:insta-service-registry.latest
          cd ../insta-config-server
          docker build -t leezonghan19/happysocial-backend:insta-config-server.latest .
          docker push leezonghan19/happysocial-backend:insta-config-server.latest
          cd ../insta-gateway-service
          docker build -t leezonghan19/happysocial-backend:insta-gateway-service.latest .
          docker push leezonghan19/happysocial-backend:insta-gateway-service.latest
          cd ../insta-auth-service
          docker build -t leezonghan19/happysocial-backend:insta-auth-service.latest .
          docker push leezonghan19/happysocial-backend:insta-auth-service.latest
          cd ../insta-user-service
          docker build -t leezonghan19/happysocial-backend:insta-user-service.latest .
          docker push leezonghan19/happysocial-backend:insta-user-service.latest
          cd ../insta-post-service
          docker build -t leezonghan19/happysocial-backend:insta-post-service.latest .
          docker push leezonghan19/happysocial-backend:insta-post-service.latest
          cd ../insta-media-service
          docker build -t leezonghan19/happysocial-backend:insta-media-service.latest .
          docker push leezonghan19/happysocial-backend:insta-media-service.latest

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      # - name: Update dependency graph
      # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
